name = "weather-api-worker"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

# [env.production]
# # The ID of the domain to deploying to
# zone_id = "$yourZoneId"

# # The route pattern your Workers application will be served at
# route = "example.com/*"
